import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "@/Components/Header";
import { Suspense } from "react";
import { Providers } from "@/redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <Providers>
        <Suspense fallback={null}>
        <Header />
        </Suspense>
        {children}
        </Providers>
        </body>
    </html>
  );
}
